site_name: ~JingYu
site_url: https://jrunkening.github.io/jrunkening

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme)"  # Palette toggle for automatic mode
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"  # Palette toggle for light mode
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  # Palette toggle for dark mode
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  logo: assets/wizard_goose_rembg.png
  favicon: assets/wizard_goose_rembg.png

plugins:
  - tags
  - search
  - glightbox

markdown_extensions:

  # images
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

  # math
  - pymdownx.arithmatex:
      generic: true

  # lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:

  # math
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
